### ISSUE TITLE
Document how to generate pot files

### ISSUE THREAD

**Issue by alexanderkjall** [justinas/gettext#12]
I'm currently adding translations to my rust application, and I'm having a hard time getting any tools to generate the .pot files.

It would be very helpful to have some documentation on the whole workflow.

**Comment by elegaanz** [comment]
I made a crate that can generate them at compile time for you, called `gettext-macros`, if you are a bit adventurous (because it may still have bugs).

**Comment by alexanderkjall** [comment]
I found that and that looks exactly like what I need :)

Sadly it uses unstable features and is therefore not usable, since the program is packaged in different distributions.

But I did manage to get xgettext working with this crate by rewriting the multiline rust strings to a single line.

this is how I get the strings out:

```
xgettext cursive/src/*rs -kgettext --sort-output -o cursive/res/ripasso-cursive.pot

msgmerge --update cursive/res/sv.po cursive/res/ripasso-cursive.pot
msgmerge --update cursive/res/nb.po cursive/res/ripasso-cursive.pot
```

And then I translate them with the poedit application, and load the .mo files in the application at runtime. I still need to figure out a way to generate the .mo files during the build.

**Comment by justinas** [comment]
I was about to recommend Ana's crate :smiley_cat: There is apparently also [tr/xtr](https://github.com/woboq/tr) which can utilize either this crate or `gettext-rs` (FFI) under the hood.

This crate is pretty bare bones currently and does not provide tools like xgettext. Not sure whether it will gain these features or remain solely as a lower-level building block.

> I still need to figure out a way to generate the .mo files during the build.

I *think* you could shell out to `msgfmt` in your `build.rs`.

**Comment by alexanderkjall** [comment]
I wrote a blog post on how I solved the problem: https://blog.hackeriet.no/rust-and-translation-files/

Feel free to use the text however you want if you want to :)
