### ISSUE TITLE
Publish new crate release

### ISSUE THREAD

**Issue by jgarzik** [justinas/gettext#20]
It has been a while since `gettext` and `gettext-sys` have been published to the broader crate ecosystem.

My interest:  I have a large project using gettext that just broke due to built-in gettext.tar.gz build issues, https://github.com/rustcoreutils/posixutils-rs 

We are currently triaging whether to require a git repo's patch branch, or what is the best workaround.

**Comment by justinas** [comment]
Hi. Could you elaborate what the failure is? Is this with `gettext`or `gettext-sys`?

This repo implements a subset of gettext functionality in Rust, meanwhile `gettext-sys` / `gettext-rs` are bindings to the gettext C library.

**Comment by jgarzik** [comment]
This was applied to `gettext-rs`, which was mistakenly thought to be this project.  Our error; closed.
