### ISSUE TITLE
Add a method to get an empty Catalog?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [justinas/gettext#3]
I'd like to be able to construct an empty Catalog, in order to fallback for unsupported languages.  I see that there is a Catalog::new, but it's private.

Alternatively, is there a better way to do this?

**Comment by elegaanz** [comment]
I would like to help fix this issue @justinas. What is the best option according to you? Simply making methods to create and edit a `Catalog` public, making something like a `CatalogBuilder`, or something else?

**Comment by justinas** [comment]
Oops, sorry for sleeping on this issue. @BaptisteGelez, what is your use case: do you also only need an empty catalog or would you like to manipulate the catalog in other ways?

**Comment by elegaanz** [comment]
I don't personally need this feature right now :sweat_smile: (I just wanted to help with this issue). But I think just having an empty catalog is quite useless, being able to manipulate it would probably be better.

**Comment by justinas** [comment]
`Catalog::empty()` seems like a simple enough addition. However, I am wary of extending the public API (even while on `0.x`) with insert/remove/etc., as there have been suggestions for features like memory-mapping a catalog that would clash with manual manipulation of catalogs (or I just haven't thought about making these two compatible hard enough).
